<!DOCTYPE html><html lang="en" class="h-full bg-slate-25 type-d-100"><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><link rel="preload" as="image" href="/build/assets/limewireLogo-CWTx4rdZ.svg"/><link rel="preload" as="image" href="/build/assets/limewire-icon-CuSTCjU4.svg"/><meta name="theme-color" content="#00934b"/><title>Download V84_PATCH.sh | LimeWire</title><meta name="description" content="Download V84_PATCH.sh on LimeWire"/><meta property="twitter:title" content="Download V84_PATCH.sh | LimeWire"/><meta property="twitter:description" content="Download V84_PATCH.sh on LimeWire"/><meta property="twitter:image" content="https://limewire.com/img/remix/twitter_card_image_file_sharing.png"/><meta property="twitter:card" content="summary_large_image"/><meta property="twitter:site" content="@limewire"/><meta property="twitter:creator" content="@limewire"/><meta property="og:title" content="Download V84_PATCH.sh | LimeWire"/><meta property="og:description" content="Download V84_PATCH.sh on LimeWire"/><meta property="og:image" content="https://limewire.com/img/remix/twitter_card_image_file_sharing.png"/><meta property="og:type" content="website"/><meta property="og:site_name" content="LimeWire"/><link rel="apple-touch-icon" href="/apple-touch-icon.png" type="image/png" sizes="180x180"/><link rel="icon" href="/favicon-32x32.ico" sizes="32x32"/><link rel="modulepreload" href="/build/chunks/entry/entry.client-DazuTZIh.js"/><link rel="modulepreload" href="/build/chunks/chunk-EVOBXE3Y-9W61Xgs7.js"/><link rel="modulepreload" href="/build/chunks/textarea-CedQn1pA.js"/><link rel="modulepreload" href="/build/chunks/correctAssetUrl-D2U_c5iP.js"/><link rel="modulepreload" href="/build/chunks/file-sharing-provider-rzg-sq63.js"/><link rel="modulepreload" href="/build/chunks/sentry-DUVkxVlL.js"/><link rel="modulepreload" href="/build/chunks/button-WTfLYYUY.js"/><link rel="modulepreload" href="/build/chunks/markdown-Q_5dIudW.js"/><link rel="modulepreload" href="/build/chunks/index-kJLDGboo.js"/><link rel="modulepreload" href="/build/chunks/PaymentTypeEnum-BIW0bXfI.js"/><link rel="modulepreload" href="/build/chunks/error-CMZhxXBr.js"/><link rel="modulepreload" href="/build/chunks/toggle-group-kkI2GucT.js"/><link rel="modulepreload" href="/build/chunks/StripeModal-CVKIXlVh.js"/><link rel="modulepreload" href="/build/chunks/focus-visible-outline-D4EmqDoY.js"/><link rel="modulepreload" href="/build/chunks/footer-CLzIvnb5.js"/><link rel="modulepreload" href="/build/chunks/link-button-0u0k6ShQ.js"/><link rel="modulepreload" href="/build/chunks/single-form-usecase-models-BCWFmCu0.js"/><link rel="modulepreload" href="/build/chunks/use-ai-studio-navigate-DtnkK9vM.js"/><link rel="modulepreload" href="/build/chunks/plus-icon-BzkK1_R0.js"/><link rel="modulepreload" href="/build/chunks/arrow-right-icon-MKNL3ZLR.js"/><link rel="modulepreload" href="/build/chunks/navigation-tabs-2caq_oyG.js"/><link rel="modulepreload" href="/build/chunks/forward-platform-action-B7m92-wH.js"/><link rel="modulepreload" href="/build/chunks/use-callback-ref-FXC1dIJW.js"/><link rel="modulepreload" href="/build/chunks/alert-BuFjbp8h.js"/><link rel="modulepreload" href="/build/chunks/base-button-Dn-aSjlR.js"/><link rel="modulepreload" href="/build/chunks/use-state-ref-2F-FBlDX.js"/><link rel="modulepreload" href="/build/chunks/result-CAafE33N.js"/><link rel="modulepreload" href="/build/chunks/get-api-GQqJvRNy.js"/><link rel="modulepreload" href="/build/chunks/resolve-to-node-Bl44lgnH.js"/><link rel="modulepreload" href="/build/chunks/noop-BjFrJKj1.js"/><link rel="modulepreload" href="/build/chunks/startWith-D6GmgBIa.js"/><link rel="modulepreload" href="/build/chunks/firstValueFrom-A2B9aB4_.js"/><link rel="modulepreload" href="/build/chunks/mergeWith-CW1bjSkm.js"/><link rel="modulepreload" href="/build/chunks/merge-sFKZucBs.js"/><link rel="modulepreload" href="/build/chunks/BehaviorSubject-DXmu5-9D.js"/><link rel="modulepreload" href="/build/chunks/runtime-a9fv597q.js"/><link rel="modulepreload" href="/build/chunks/runtime-2_b2CLRu.js"/><link rel="modulepreload" href="/build/chunks/VerificationStatusEnum-BMWjV5ER.js"/><link rel="modulepreload" href="/build/chunks/AccountSubscriptionTier-Cz37hh3K.js"/><link rel="modulepreload" href="/build/chunks/UsStateCodeAlpha2-JNjTMX_I.js"/><link rel="modulepreload" href="/build/chunks/combineLatest-B-eaUnSB.js"/><link rel="modulepreload" href="/build/chunks/form-schema-utils-BpIBEm7l.js"/><link rel="modulepreload" href="/build/chunks/types-DL0SRdtb.js"/><link rel="modulepreload" href="/build/chunks/modal-content-window-title-header-B4KyUpSA.js"/><link rel="modulepreload" href="/build/chunks/form-validation-BVQTbEu8.js"/><link rel="modulepreload" href="/build/chunks/use-self-cancel-timeout-CylTudUM.js"/><link rel="modulepreload" href="/build/chunks/use-self-cancel-interval-Dvxku-cX.js"/><link rel="modulepreload" href="/build/chunks/createFormData-DNO6HZGs.js"/><link rel="modulepreload" href="/build/chunks/preload-helper-ckwbz45p.js"/><link rel="modulepreload" href="/build/chunks/create-lazy-singleton-nczC2Aqe.js"/><link rel="modulepreload" href="/build/chunks/env-context-Crfubjd7.js"/><link rel="modulepreload" href="/build/chunks/actionable-elements-BiUyVnPQ.js"/><link rel="modulepreload" href="/build/chunks/get-sharing-bucket-expiration-label-CzomMGXb.js"/><link rel="modulepreload" href="/build/chunks/auth-form-PuyrRK6N.js"/><link rel="modulepreload" href="/build/chunks/use-typed-explicit-fetcher-8EVVP3LO.js"/><link rel="modulepreload" href="/build/chunks/use-issue-two-factor-code-C-lTNfXJ.js"/><link rel="modulepreload" href="/build/chunks/authenticity-token-jepGkwPV.js"/><link rel="modulepreload" href="/build/chunks/auth-form-validation-BU6Liuu6.js"/><link rel="modulepreload" href="/build/chunks/use-const-Ctj4Pbrd.js"/><link rel="modulepreload" href="/build/chunks/auth-context-C4B4EndV.js"/><link rel="modulepreload" href="/build/chunks/navigation-link-Dew0cAKK.js"/><link rel="modulepreload" href="/build/chunks/app-integration-provider-eroOOUkO.js"/><link rel="modulepreload" href="/build/chunks/app-integration-loading-Stpofhhd.js"/><link rel="modulepreload" href="/build/chunks/client-only-BczqNwUQ.js"/><link rel="modulepreload" href="/build/chunks/auth-window-messenger-BT_sk8fK.js"/><link rel="modulepreload" href="/build/chunks/use-external-wallet-d47QtwzM.js"/><link rel="modulepreload" href="/build/chunks/divider-Rf5dTIjq.js"/><link rel="modulepreload" href="/build/chunks/user-context-DcxnCGfr.js"/><link rel="modulepreload" href="/build/chunks/format-crypto-currency-ywX7BMAm.js"/><link rel="modulepreload" href="/build/chunks/CryptoCurrency-H89N9OUl.js"/><link rel="modulepreload" href="/build/chunks/index-C_cZ4Myj.js"/><link rel="modulepreload" href="/build/chunks/lmwr-context-gGILrNJS.js"/><link rel="modulepreload" href="/build/chunks/api-context-CI3M1bMX.js"/><link rel="modulepreload" href="/build/chunks/contract-DCyJtHIA.js"/><link rel="modulepreload" href="/build/chunks/shared-DwIwScEe.js"/><link rel="modulepreload" href="/build/chunks/use-copyright-DfriYUUN.js"/><link rel="modulepreload" href="/build/chunks/draw-fit-image-9IJk8zjc.js"/><link rel="modulepreload" href="/build/chunks/ai-studio-session-params-CvRPbapa.js"/><link rel="modulepreload" href="/build/chunks/tab-button-B9masPp5.js"/><link rel="modulepreload" href="/build/chunks/content-item-icon-CWSsBIAk.js"/><link rel="modulepreload" href="/build/chunks/content-item-name-DlF1OtJB.js"/><link rel="modulepreload" href="/build/chunks/feedback-tooltip-DzcbJ7Uo.js"/><link rel="modulepreload" href="/build/chunks/file-name-wPVW7C-B.js"/><link rel="modulepreload" href="/build/chunks/dropdown-menu-item-DBh_jOFm.js"/><link rel="modulepreload" href="/build/chunks/CompositeItem-CDHQO3Bq.js"/><link rel="modulepreload" href="/build/chunks/file-descriptor-6NH0AYhf.js"/><link rel="modulepreload" href="/build/chunks/format-4Kq6c7g1.js"/><link rel="modulepreload" href="/build/chunks/entry/root-B1f1mDU1.js"/><link rel="modulepreload" href="/build/chunks/use-sentry-capture-route-error-C41R5BR6.js"/><link rel="modulepreload" href="/build/chunks/page-error-BJg5EwrZ.js"/><link rel="modulepreload" href="/build/chunks/page-error-content-C6qE9j0k.js"/><link rel="modulepreload" href="/build/chunks/default-shell-layout-Cm20i_GI.js"/><link rel="modulepreload" href="/build/chunks/creator-name-CljkNgas.js"/><link rel="modulepreload" href="/build/chunks/asset-aspect-ratio-BohSO0Ps.js"/><link rel="modulepreload" href="/build/chunks/limewire-logo-Dqzw9EF0.js"/><link rel="modulepreload" href="/build/chunks/use-logout-2r9-Iv6K.js"/><link rel="modulepreload" href="/build/chunks/creator-DZkRxswE.js"/><link rel="modulepreload" href="/build/chunks/errors-DVvSrYRD.js"/><link rel="modulepreload" href="/build/chunks/entry/__root-t3SG9b72.js"/><link rel="modulepreload" href="/build/chunks/QueryClientProvider-eTMApExI.js"/><link rel="modulepreload" href="/build/chunks/use-sse-CIElAM2L.js"/><link rel="modulepreload" href="/build/chunks/share-nearby-provider-z51Inzez.js"/><link rel="modulepreload" href="/build/chunks/page-error-404-DzJrfiEl.js"/><link rel="modulepreload" href="/build/chunks/script-AKGWJTdR.js"/><link rel="modulepreload" href="/build/chunks/copy-input-CuB6aqkr.js"/><link rel="modulepreload" href="/build/chunks/page-error-404-Ba3LfCNG.js"/><link rel="modulepreload" href="/build/chunks/entry/_id-ZQxUIa8-.js"/><link rel="modulepreload" href="/build/chunks/google-adsense-ad-aPLRVnSn.js"/><link rel="modulepreload" href="/build/chunks/page-column-layout-7pRCrlts.js"/><link rel="modulepreload" href="/build/chunks/get-default-seo-preview-image-CuRl7GKl.js"/><link rel="modulepreload" href="/build/chunks/limewireLogo-RvAqqAY_.js"/><link rel="modulepreload" href="/build/chunks/use-endless-scroll-BXQnXQea.js"/><link rel="modulepreload" href="/build/chunks/textarea-keydown-enter-submit-CipxD2L_.js"/><link rel="modulepreload" href="/build/chunks/date-time-ls5LZsUX.js"/><link rel="modulepreload" href="/build/chunks/root-data-from-meta-D6MxA-wH.js"/><link rel="stylesheet" href="/build/assets/nprogress-Dw03ZESa.css"/><link rel="stylesheet" href="/build/assets/react-datepicker-CE21K4bl.css"/><link rel="stylesheet" href="/build/assets/400-C8LWbix3.css"/><link rel="stylesheet" href="/build/assets/500-B36wLJV3.css"/><link rel="stylesheet" href="/build/assets/700-C5Ia9mPP.css"/><link rel="stylesheet" href="/build/assets/tailwind-C3yE5gDo.css"/></head><body class="h-full"><div style="--lmwr-banner-height:0px;--lmwr-navigation-height:3.5rem;--lmwr-navigation-sticky-height:calc(var(--lmwr-navigation-height) * var(--lmwr-navigation-non-sticky-height-percent, 1))" class="min-h-full grid grid-cols-1 grid-rows-[auto_auto_minmax(0,_1fr)]"><div class="z-50"></div><div class="h-[--lmwr-navigation-height] z-40 sticky top-0"><nav class="h-full bg-slate-25 after:content-empty after:absolute after:w-full after:h-px after:bg-slate-200 after:bottom-0"><div class="flex items-center gap-x-3 h-full min-w-0 px-3.5 md:px-4"><div class="flex items-center h-full min-w-0 flex-none"><a class="hidden md:flex h-10 outline-offset-0 flex-none items-center rounded-sm" href="/" data-discover="true"><img class="w-32 object-contain" src="/build/assets/limewireLogo-CWTx4rdZ.svg" alt="LimeWire Logo"/></a><a class="flex md:hidden h-10 outline-offset-0 flex-none items-center rounded-sm" href="/" data-discover="true"><img class="w-8 object-contain" src="/build/assets/limewire-icon-CuSTCjU4.svg" alt="LimeWire Logo"/></a></div><div class="h-6 flex items-center min-w-0"><div class="lg:flex-none flex-1 min-w-0 h-full flex items-center border-l-slate-300 border-l pl-3"><span style="clip:rect(0 0 0 0);overflow:hidden;white-space:nowrap;position:fixed;top:0;left:0;border:0;padding:0;width:1px;height:1px;margin:-1px" aria-hidden="true" tabindex="0" data-base-ui-focus-guard=""></span><button type="button" tabindex="0" data-base-ui-click-trigger="" id="base-ui-_R_1mkimqj5_" class="default:rounded-sm block h-10 text-slate-900 min-w-0 w-full"><span class="flex flex-row items-center gap-x-2 min-w-0"><span style="mask-image:url(/build/assets/sharing-bucket-single-file-icon-CoFWt95U.svg);-webkit-mask-image:url(/build/assets/sharing-bucket-single-file-icon-CoFWt95U.svg)" class="default:block default:flex-none default:bg-current mask-center mask-contain mask-no-repeat w-4 h-4 text-slate-700 flex-none hidden lg:block"></span><span class="min-w-0 max-w-64 flex-1"><span style="clip:rect(0 0 0 0);overflow:hidden;white-space:nowrap;position:fixed;top:0;left:0;border:0;padding:0;width:1px;height:1px;margin:-1px" aria-hidden="true" tabindex="0" data-base-ui-focus-guard=""></span><span class="default:type-d-50 default:text-slate-900 default:overflow-hidden flex flex-row items-center flex-nowrap min-w-0 type-d-100-medium"><span class="overflow-hidden text-ellipsis whitespace-nowrap">V84_PATCH</span><span class="flex-none whitespace-nowrap">.sh</span></span><span style="clip:rect(0 0 0 0);overflow:hidden;white-space:nowrap;position:fixed;top:0;left:0;border:0;padding:0;width:1px;height:1px;margin:-1px" aria-hidden="true" tabindex="0" data-base-ui-focus-guard=""></span></span><span style="mask-image:url(/build/assets/chevron-down-icon-gfhbPJjL.svg);-webkit-mask-image:url(/build/assets/chevron-down-icon-gfhbPJjL.svg)" class="default:block default:flex-none default:bg-current mask-center mask-contain mask-no-repeat w-4 h-4 transition-transform"></span></span></button><span style="clip:rect(0 0 0 0);overflow:hidden;white-space:nowrap;position:fixed;top:0;left:0;border:0;padding:0;width:1px;height:1px;margin:-1px" aria-hidden="true" tabindex="0" data-base-ui-focus-guard=""></span></div><div class="h-full max-w-56 flex items-center flex-none type-d-75 text-slate-500 border-l-slate-300 border-l ml-3 pl-3"><div class="text-nowrap overflow-hidden text-ellipsis min-w-0">13.4KB</div></div><div class="h-full lg:flex-1 hidden lg:flex items-center min-w-0 flex-wrap overflow-hidden"><div class="h-full"></div><div class="h-full max-w-56 flex items-center flex-none type-d-75 text-slate-500 border-l-slate-300 border-l ml-3 pl-3"><div class="text-nowrap overflow-hidden text-ellipsis min-w-0"><span class="bg-slate-300 h-5 rounded-md block w-28"></span></div></div><div class="h-full max-w-56 flex items-center flex-none type-d-75 text-slate-500 border-l-slate-300 border-l ml-3 pl-3"><div class="text-nowrap overflow-hidden text-ellipsis min-w-0"><span class="bg-slate-300 h-5 rounded-md block w-24"></span></div></div></div></div><div class="flex items-center h-full flex-none min-w-0 ml-auto gap-x-2"><div><div class="md:hidden w-10 h-10 bg-slate-300 rounded-full"></div><div class="hidden md:flex w-32 h-10 bg-slate-300 rounded-full"></div></div><div class="items-center flex-none gap-x-2 hidden sm:flex"><div><div class="lg:hidden w-10 h-10 bg-slate-300 rounded-full"></div><div class="hidden lg:flex w-28 h-10 bg-slate-300 rounded-full"></div></div><div class="w-10 h-10 bg-slate-300 rounded-full"></div><div class="w-10 h-10 bg-slate-300 rounded-full"></div></div></div></div></nav></div><div><div class="default:min-h-full grid"><div class="w-full h-full grid grid-cols-1 grid-rows-1 md:grid-cols-[minmax(0,1fr)]"><main class="w-full min-h-full"><div class="h-full w-full flex items-center justify-center"><span class="default:w-5 default:h-5 default:border-2 animate-spin block border-t-current border-r-current border-solid border-b-transparent border-l-transparent rounded-full w-7 h-7"></span></div></main></div></div></div></div><div class="lg:hidden fixed top-0 left-0 overflow-hidden pointer-events-none -z-50"></div><script>
function __removeSearchParam() {
  try {
    var url = new URL(window.location.href);
    if (url.searchParams.has("lmwr-ftv")) {
      url.searchParams.delete("lmwr-ftv");
      window.history.replaceState(null, "", url.href);
    } 
  } catch (e) {}
}
__removeSearchParam();
</script><script>window.ENV = {"NOW":"2026-05-05T17:01:38.958Z","CLIENT_BASE_URL":"https://limewire.com","IS_DEV":false,"IS_STAGING":false,"API_BASE_URL":"https://api.limewire.com","GA_TRACKING_ID":"GTM-NNHHMZ9","LIMEWIRE_FREE_USER_ID":"7f219511-0a09-403c-a94b-caa56419b5f8","LIMEWIRE_PRO_USER_ID":"1e2c66a9-7073-499b-86fb-b134a088ce44","SENTRY_DSN":"https://3914d239cc544007a8bc3b33c2e276e7:375389f9b8fc4a58aac7ddf053335cd6@o4505008135340032.ingest.sentry.io/4505114707099648","SENTRY_ENVIRONMENT":"production","SENTRY_PROJECT":"limewire-js-remix","GIT_RELEASE":"e0f62ac00c91b4e3883a5c03915e94bfbcb608c0","STORYBLOCK_SPACE_ACCESS_TOKEN":"jmGRmWycHD5MvliLQXFkXAtt"}</script><script>window.__reactRouterContext = {"basename":"/","future":{"unstable_optimizeDeps":false,"unstable_passThroughRequests":false,"unstable_subResourceIntegrity":false,"unstable_trailingSlashAwareDataRequests":false,"unstable_previewServerPrerendering":false,"v8_middleware":false,"v8_splitRouteModules":false,"v8_viteEnvironmentApi":false},"routeDiscovery":{"mode":"lazy","manifestPath":"/__manifest"},"ssr":true,"isSpaMode":false};window.__reactRouterContext.stream = new ReadableStream({start(controller){window.__reactRouterContext.streamController = controller;}}).pipeThrough(new TextEncoderStream());</script><script type="module" async="">;
import * as route0 from "/build/chunks/entry/root-B1f1mDU1.js";
import * as route1 from "/build/chunks/entry/__root-t3SG9b72.js";
import * as route2 from "/build/chunks/entry/_id-ZQxUIa8-.js";
  window.__reactRouterManifest = {
  "entry": {
    "module": "/build/chunks/entry/entry.client-DazuTZIh.js",
    "imports": [
      "/build/chunks/chunk-EVOBXE3Y-9W61Xgs7.js",
      "/build/chunks/textarea-CedQn1pA.js",
      "/build/chunks/correctAssetUrl-D2U_c5iP.js",
      "/build/chunks/file-sharing-provider-rzg-sq63.js",
      "/build/chunks/sentry-DUVkxVlL.js",
      "/build/chunks/button-WTfLYYUY.js",
      "/build/chunks/markdown-Q_5dIudW.js",
      "/build/chunks/index-kJLDGboo.js",
      "/build/chunks/PaymentTypeEnum-BIW0bXfI.js",
      "/build/chunks/error-CMZhxXBr.js",
      "/build/chunks/toggle-group-kkI2GucT.js",
      "/build/chunks/StripeModal-CVKIXlVh.js",
      "/build/chunks/focus-visible-outline-D4EmqDoY.js",
      "/build/chunks/footer-CLzIvnb5.js",
      "/build/chunks/link-button-0u0k6ShQ.js",
      "/build/chunks/single-form-usecase-models-BCWFmCu0.js",
      "/build/chunks/use-ai-studio-navigate-DtnkK9vM.js",
      "/build/chunks/plus-icon-BzkK1_R0.js",
      "/build/chunks/arrow-right-icon-MKNL3ZLR.js",
      "/build/chunks/navigation-tabs-2caq_oyG.js",
      "/build/chunks/forward-platform-action-B7m92-wH.js",
      "/build/chunks/use-callback-ref-FXC1dIJW.js",
      "/build/chunks/alert-BuFjbp8h.js",
      "/build/chunks/base-button-Dn-aSjlR.js",
      "/build/chunks/use-state-ref-2F-FBlDX.js",
      "/build/chunks/result-CAafE33N.js",
      "/build/chunks/get-api-GQqJvRNy.js",
      "/build/chunks/resolve-to-node-Bl44lgnH.js",
      "/build/chunks/noop-BjFrJKj1.js",
      "/build/chunks/startWith-D6GmgBIa.js",
      "/build/chunks/firstValueFrom-A2B9aB4_.js",
      "/build/chunks/mergeWith-CW1bjSkm.js",
      "/build/chunks/merge-sFKZucBs.js",
      "/build/chunks/BehaviorSubject-DXmu5-9D.js",
      "/build/chunks/runtime-a9fv597q.js",
      "/build/chunks/runtime-2_b2CLRu.js",
      "/build/chunks/VerificationStatusEnum-BMWjV5ER.js",
      "/build/chunks/AccountSubscriptionTier-Cz37hh3K.js",
      "/build/chunks/UsStateCodeAlpha2-JNjTMX_I.js",
      "/build/chunks/combineLatest-B-eaUnSB.js",
      "/build/chunks/form-schema-utils-BpIBEm7l.js",
      "/build/chunks/types-DL0SRdtb.js",
      "/build/chunks/modal-content-window-title-header-B4KyUpSA.js",
      "/build/chunks/form-validation-BVQTbEu8.js",
      "/build/chunks/use-self-cancel-timeout-CylTudUM.js",
      "/build/chunks/use-self-cancel-interval-Dvxku-cX.js",
      "/build/chunks/createFormData-DNO6HZGs.js",
      "/build/chunks/preload-helper-ckwbz45p.js",
      "/build/chunks/create-lazy-singleton-nczC2Aqe.js",
      "/build/chunks/env-context-Crfubjd7.js",
      "/build/chunks/actionable-elements-BiUyVnPQ.js",
      "/build/chunks/get-sharing-bucket-expiration-label-CzomMGXb.js",
      "/build/chunks/auth-form-PuyrRK6N.js",
      "/build/chunks/use-typed-explicit-fetcher-8EVVP3LO.js",
      "/build/chunks/use-issue-two-factor-code-C-lTNfXJ.js",
      "/build/chunks/authenticity-token-jepGkwPV.js",
      "/build/chunks/auth-form-validation-BU6Liuu6.js",
      "/build/chunks/use-const-Ctj4Pbrd.js",
      "/build/chunks/auth-context-C4B4EndV.js",
      "/build/chunks/navigation-link-Dew0cAKK.js",
      "/build/chunks/app-integration-provider-eroOOUkO.js",
      "/build/chunks/app-integration-loading-Stpofhhd.js",
      "/build/chunks/client-only-BczqNwUQ.js",
      "/build/chunks/auth-window-messenger-BT_sk8fK.js",
      "/build/chunks/use-external-wallet-d47QtwzM.js",
      "/build/chunks/divider-Rf5dTIjq.js",
      "/build/chunks/user-context-DcxnCGfr.js",
      "/build/chunks/format-crypto-currency-ywX7BMAm.js",
      "/build/chunks/CryptoCurrency-H89N9OUl.js",
      "/build/chunks/index-C_cZ4Myj.js",
      "/build/chunks/lmwr-context-gGILrNJS.js",
      "/build/chunks/api-context-CI3M1bMX.js",
      "/build/chunks/contract-DCyJtHIA.js",
      "/build/chunks/shared-DwIwScEe.js",
      "/build/chunks/use-copyright-DfriYUUN.js",
      "/build/chunks/draw-fit-image-9IJk8zjc.js",
      "/build/chunks/ai-studio-session-params-CvRPbapa.js",
      "/build/chunks/tab-button-B9masPp5.js",
      "/build/chunks/content-item-icon-CWSsBIAk.js",
      "/build/chunks/content-item-name-DlF1OtJB.js",
      "/build/chunks/feedback-tooltip-DzcbJ7Uo.js",
      "/build/chunks/file-name-wPVW7C-B.js",
      "/build/chunks/dropdown-menu-item-DBh_jOFm.js",
      "/build/chunks/CompositeItem-CDHQO3Bq.js",
      "/build/chunks/file-descriptor-6NH0AYhf.js",
      "/build/chunks/format-4Kq6c7g1.js"
    ],
    "css": []
  },
  "routes": {
    "root": {
      "id": "root",
      "path": "",
      "hasAction": false,
      "hasLoader": false,
      "hasClientAction": false,
      "hasClientLoader": false,
      "hasClientMiddleware": false,
      "hasDefaultExport": true,
      "hasErrorBoundary": true,
      "module": "/build/chunks/entry/root-B1f1mDU1.js",
      "imports": [
        "/build/chunks/chunk-EVOBXE3Y-9W61Xgs7.js",
        "/build/chunks/textarea-CedQn1pA.js",
        "/build/chunks/correctAssetUrl-D2U_c5iP.js",
        "/build/chunks/file-sharing-provider-rzg-sq63.js",
        "/build/chunks/sentry-DUVkxVlL.js",
        "/build/chunks/button-WTfLYYUY.js",
        "/build/chunks/markdown-Q_5dIudW.js",
        "/build/chunks/index-kJLDGboo.js",
        "/build/chunks/PaymentTypeEnum-BIW0bXfI.js",
        "/build/chunks/error-CMZhxXBr.js",
        "/build/chunks/toggle-group-kkI2GucT.js",
        "/build/chunks/StripeModal-CVKIXlVh.js",
        "/build/chunks/focus-visible-outline-D4EmqDoY.js",
        "/build/chunks/footer-CLzIvnb5.js",
        "/build/chunks/link-button-0u0k6ShQ.js",
        "/build/chunks/single-form-usecase-models-BCWFmCu0.js",
        "/build/chunks/use-ai-studio-navigate-DtnkK9vM.js",
        "/build/chunks/plus-icon-BzkK1_R0.js",
        "/build/chunks/arrow-right-icon-MKNL3ZLR.js",
        "/build/chunks/navigation-tabs-2caq_oyG.js",
        "/build/chunks/forward-platform-action-B7m92-wH.js",
        "/build/chunks/use-callback-ref-FXC1dIJW.js",
        "/build/chunks/alert-BuFjbp8h.js",
        "/build/chunks/base-button-Dn-aSjlR.js",
        "/build/chunks/use-state-ref-2F-FBlDX.js",
        "/build/chunks/result-CAafE33N.js",
        "/build/chunks/get-api-GQqJvRNy.js",
        "/build/chunks/resolve-to-node-Bl44lgnH.js",
        "/build/chunks/noop-BjFrJKj1.js",
        "/build/chunks/startWith-D6GmgBIa.js",
        "/build/chunks/firstValueFrom-A2B9aB4_.js",
        "/build/chunks/mergeWith-CW1bjSkm.js",
        "/build/chunks/merge-sFKZucBs.js",
        "/build/chunks/BehaviorSubject-DXmu5-9D.js",
        "/build/chunks/runtime-a9fv597q.js",
        "/build/chunks/runtime-2_b2CLRu.js",
        "/build/chunks/VerificationStatusEnum-BMWjV5ER.js",
        "/build/chunks/AccountSubscriptionTier-Cz37hh3K.js",
        "/build/chunks/UsStateCodeAlpha2-JNjTMX_I.js",
        "/build/chunks/combineLatest-B-eaUnSB.js",
        "/build/chunks/form-schema-utils-BpIBEm7l.js",
        "/build/chunks/types-DL0SRdtb.js",
        "/build/chunks/modal-content-window-title-header-B4KyUpSA.js",
        "/build/chunks/form-validation-BVQTbEu8.js",
        "/build/chunks/use-self-cancel-timeout-CylTudUM.js",
        "/build/chunks/use-self-cancel-interval-Dvxku-cX.js",
        "/build/chunks/createFormData-DNO6HZGs.js",
        "/build/chunks/preload-helper-ckwbz45p.js",
        "/build/chunks/create-lazy-singleton-nczC2Aqe.js",
        "/build/chunks/env-context-Crfubjd7.js",
        "/build/chunks/actionable-elements-BiUyVnPQ.js",
        "/build/chunks/get-sharing-bucket-expiration-label-CzomMGXb.js",
        "/build/chunks/auth-form-PuyrRK6N.js",
        "/build/chunks/use-typed-explicit-fetcher-8EVVP3LO.js",
        "/build/chunks/use-issue-two-factor-code-C-lTNfXJ.js",
        "/build/chunks/authenticity-token-jepGkwPV.js",
        "/build/chunks/auth-form-validation-BU6Liuu6.js",
        "/build/chunks/use-const-Ctj4Pbrd.js",
        "/build/chunks/auth-context-C4B4EndV.js",
        "/build/chunks/navigation-link-Dew0cAKK.js",
        "/build/chunks/app-integration-provider-eroOOUkO.js",
        "/build/chunks/app-integration-loading-Stpofhhd.js",
        "/build/chunks/client-only-BczqNwUQ.js",
        "/build/chunks/auth-window-messenger-BT_sk8fK.js",
        "/build/chunks/use-external-wallet-d47QtwzM.js",
        "/build/chunks/divider-Rf5dTIjq.js",
        "/build/chunks/user-context-DcxnCGfr.js",
        "/build/chunks/format-crypto-currency-ywX7BMAm.js",
        "/build/chunks/CryptoCurrency-H89N9OUl.js",
        "/build/chunks/index-C_cZ4Myj.js",
        "/build/chunks/lmwr-context-gGILrNJS.js",
        "/build/chunks/api-context-CI3M1bMX.js",
        "/build/chunks/contract-DCyJtHIA.js",
        "/build/chunks/shared-DwIwScEe.js",
        "/build/chunks/use-copyright-DfriYUUN.js",
        "/build/chunks/draw-fit-image-9IJk8zjc.js",
        "/build/chunks/ai-studio-session-params-CvRPbapa.js",
        "/build/chunks/tab-button-B9masPp5.js",
        "/build/chunks/content-item-icon-CWSsBIAk.js",
        "/build/chunks/content-item-name-DlF1OtJB.js",
        "/build/chunks/feedback-tooltip-DzcbJ7Uo.js",
        "/build/chunks/file-name-wPVW7C-B.js",
        "/build/chunks/dropdown-menu-item-DBh_jOFm.js",
        "/build/chunks/CompositeItem-CDHQO3Bq.js",
        "/build/chunks/file-descriptor-6NH0AYhf.js",
        "/build/chunks/format-4Kq6c7g1.js",
        "/build/chunks/use-sentry-capture-route-error-C41R5BR6.js",
        "/build/chunks/page-error-BJg5EwrZ.js",
        "/build/chunks/page-error-content-C6qE9j0k.js",
        "/build/chunks/default-shell-layout-Cm20i_GI.js",
        "/build/chunks/creator-name-CljkNgas.js",
        "/build/chunks/asset-aspect-ratio-BohSO0Ps.js",
        "/build/chunks/limewire-logo-Dqzw9EF0.js",
        "/build/chunks/use-logout-2r9-Iv6K.js",
        "/build/chunks/creator-DZkRxswE.js",
        "/build/chunks/errors-DVvSrYRD.js"
      ],
      "css": []
    },
    "routes/__root": {
      "id": "routes/__root",
      "parentId": "root",
      "hasAction": false,
      "hasLoader": true,
      "hasClientAction": false,
      "hasClientLoader": false,
      "hasClientMiddleware": false,
      "hasDefaultExport": true,
      "hasErrorBoundary": true,
      "module": "/build/chunks/entry/__root-t3SG9b72.js",
      "imports": [
        "/build/chunks/chunk-EVOBXE3Y-9W61Xgs7.js",
        "/build/chunks/authenticity-token-jepGkwPV.js",
        "/build/chunks/runtime-2_b2CLRu.js",
        "/build/chunks/AccountSubscriptionTier-Cz37hh3K.js",
        "/build/chunks/QueryClientProvider-eTMApExI.js",
        "/build/chunks/lmwr-context-gGILrNJS.js",
        "/build/chunks/env-context-Crfubjd7.js",
        "/build/chunks/auth-context-C4B4EndV.js",
        "/build/chunks/user-context-DcxnCGfr.js",
        "/build/chunks/StripeModal-CVKIXlVh.js",
        "/build/chunks/createFormData-DNO6HZGs.js",
        "/build/chunks/sentry-DUVkxVlL.js",
        "/build/chunks/use-sse-CIElAM2L.js",
        "/build/chunks/textarea-CedQn1pA.js",
        "/build/chunks/file-sharing-provider-rzg-sq63.js",
        "/build/chunks/index-kJLDGboo.js",
        "/build/chunks/modal-content-window-title-header-B4KyUpSA.js",
        "/build/chunks/file-name-wPVW7C-B.js",
        "/build/chunks/focus-visible-outline-D4EmqDoY.js",
        "/build/chunks/get-sharing-bucket-expiration-label-CzomMGXb.js",
        "/build/chunks/result-CAafE33N.js",
        "/build/chunks/get-api-GQqJvRNy.js",
        "/build/chunks/content-item-icon-CWSsBIAk.js",
        "/build/chunks/preload-helper-ckwbz45p.js",
        "/build/chunks/draw-fit-image-9IJk8zjc.js",
        "/build/chunks/noop-BjFrJKj1.js",
        "/build/chunks/file-descriptor-6NH0AYhf.js",
        "/build/chunks/form-validation-BVQTbEu8.js",
        "/build/chunks/default-shell-layout-Cm20i_GI.js",
        "/build/chunks/toggle-group-kkI2GucT.js",
        "/build/chunks/use-callback-ref-FXC1dIJW.js",
        "/build/chunks/client-only-BczqNwUQ.js",
        "/build/chunks/runtime-a9fv597q.js",
        "/build/chunks/api-context-CI3M1bMX.js",
        "/build/chunks/share-nearby-provider-z51Inzez.js",
        "/build/chunks/auth-form-PuyrRK6N.js",
        "/build/chunks/use-logout-2r9-Iv6K.js",
        "/build/chunks/alert-BuFjbp8h.js",
        "/build/chunks/button-WTfLYYUY.js",
        "/build/chunks/app-integration-provider-eroOOUkO.js",
        "/build/chunks/use-sentry-capture-route-error-C41R5BR6.js",
        "/build/chunks/page-error-404-DzJrfiEl.js",
        "/build/chunks/script-AKGWJTdR.js",
        "/build/chunks/format-crypto-currency-ywX7BMAm.js",
        "/build/chunks/CryptoCurrency-H89N9OUl.js",
        "/build/chunks/error-CMZhxXBr.js",
        "/build/chunks/use-state-ref-2F-FBlDX.js",
        "/build/chunks/use-const-Ctj4Pbrd.js",
        "/build/chunks/base-button-Dn-aSjlR.js",
        "/build/chunks/types-DL0SRdtb.js",
        "/build/chunks/index-C_cZ4Myj.js",
        "/build/chunks/PaymentTypeEnum-BIW0bXfI.js",
        "/build/chunks/actionable-elements-BiUyVnPQ.js",
        "/build/chunks/use-external-wallet-d47QtwzM.js",
        "/build/chunks/create-lazy-singleton-nczC2Aqe.js",
        "/build/chunks/firstValueFrom-A2B9aB4_.js",
        "/build/chunks/contract-DCyJtHIA.js",
        "/build/chunks/resolve-to-node-Bl44lgnH.js",
        "/build/chunks/startWith-D6GmgBIa.js",
        "/build/chunks/mergeWith-CW1bjSkm.js",
        "/build/chunks/merge-sFKZucBs.js",
        "/build/chunks/BehaviorSubject-DXmu5-9D.js",
        "/build/chunks/VerificationStatusEnum-BMWjV5ER.js",
        "/build/chunks/UsStateCodeAlpha2-JNjTMX_I.js",
        "/build/chunks/combineLatest-B-eaUnSB.js",
        "/build/chunks/form-schema-utils-BpIBEm7l.js",
        "/build/chunks/link-button-0u0k6ShQ.js",
        "/build/chunks/use-self-cancel-timeout-CylTudUM.js",
        "/build/chunks/use-self-cancel-interval-Dvxku-cX.js",
        "/build/chunks/navigation-link-Dew0cAKK.js",
        "/build/chunks/tab-button-B9masPp5.js",
        "/build/chunks/creator-name-CljkNgas.js",
        "/build/chunks/asset-aspect-ratio-BohSO0Ps.js",
        "/build/chunks/shared-DwIwScEe.js",
        "/build/chunks/limewire-logo-Dqzw9EF0.js",
        "/build/chunks/CompositeItem-CDHQO3Bq.js",
        "/build/chunks/arrow-right-icon-MKNL3ZLR.js",
        "/build/chunks/creator-DZkRxswE.js",
        "/build/chunks/use-copyright-DfriYUUN.js",
        "/build/chunks/copy-input-CuB6aqkr.js",
        "/build/chunks/use-typed-explicit-fetcher-8EVVP3LO.js",
        "/build/chunks/use-issue-two-factor-code-C-lTNfXJ.js",
        "/build/chunks/auth-form-validation-BU6Liuu6.js",
        "/build/chunks/app-integration-loading-Stpofhhd.js",
        "/build/chunks/auth-window-messenger-BT_sk8fK.js",
        "/build/chunks/divider-Rf5dTIjq.js",
        "/build/chunks/page-error-BJg5EwrZ.js",
        "/build/chunks/page-error-content-C6qE9j0k.js",
        "/build/chunks/errors-DVvSrYRD.js",
        "/build/chunks/page-error-404-Ba3LfCNG.js"
      ],
      "css": []
    },
    "routes/__root/d/$id": {
      "id": "routes/__root/d/$id",
      "parentId": "routes/__root",
      "path": "d/:id",
      "hasAction": false,
      "hasLoader": true,
      "hasClientAction": false,
      "hasClientLoader": false,
      "hasClientMiddleware": false,
      "hasDefaultExport": true,
      "hasErrorBoundary": false,
      "module": "/build/chunks/entry/_id-ZQxUIa8-.js",
      "imports": [
        "/build/chunks/chunk-EVOBXE3Y-9W61Xgs7.js",
        "/build/chunks/google-adsense-ad-aPLRVnSn.js",
        "/build/chunks/file-sharing-provider-rzg-sq63.js",
        "/build/chunks/page-column-layout-7pRCrlts.js",
        "/build/chunks/get-default-seo-preview-image-CuRl7GKl.js",
        "/build/chunks/page-error-content-C6qE9j0k.js",
        "/build/chunks/page-error-404-Ba3LfCNG.js",
        "/build/chunks/default-shell-layout-Cm20i_GI.js",
        "/build/chunks/index-kJLDGboo.js",
        "/build/chunks/get-api-GQqJvRNy.js",
        "/build/chunks/runtime-2_b2CLRu.js",
        "/build/chunks/runtime-a9fv597q.js",
        "/build/chunks/feedback-tooltip-DzcbJ7Uo.js",
        "/build/chunks/resolve-to-node-Bl44lgnH.js",
        "/build/chunks/alert-BuFjbp8h.js",
        "/build/chunks/content-item-name-DlF1OtJB.js",
        "/build/chunks/use-self-cancel-timeout-CylTudUM.js",
        "/build/chunks/navigation-link-Dew0cAKK.js",
        "/build/chunks/shared-DwIwScEe.js",
        "/build/chunks/limewireLogo-RvAqqAY_.js",
        "/build/chunks/file-name-wPVW7C-B.js",
        "/build/chunks/form-schema-utils-BpIBEm7l.js",
        "/build/chunks/modal-content-window-title-header-B4KyUpSA.js",
        "/build/chunks/form-validation-BVQTbEu8.js",
        "/build/chunks/button-WTfLYYUY.js",
        "/build/chunks/types-DL0SRdtb.js",
        "/build/chunks/textarea-CedQn1pA.js",
        "/build/chunks/focus-visible-outline-D4EmqDoY.js",
        "/build/chunks/base-button-Dn-aSjlR.js",
        "/build/chunks/toggle-group-kkI2GucT.js",
        "/build/chunks/use-endless-scroll-BXQnXQea.js",
        "/build/chunks/use-state-ref-2F-FBlDX.js",
        "/build/chunks/navigation-tabs-2caq_oyG.js",
        "/build/chunks/content-item-icon-CWSsBIAk.js",
        "/build/chunks/env-context-Crfubjd7.js",
        "/build/chunks/use-callback-ref-FXC1dIJW.js",
        "/build/chunks/noop-BjFrJKj1.js",
        "/build/chunks/QueryClientProvider-eTMApExI.js",
        "/build/chunks/api-context-CI3M1bMX.js",
        "/build/chunks/user-context-DcxnCGfr.js",
        "/build/chunks/creator-name-CljkNgas.js",
        "/build/chunks/use-const-Ctj4Pbrd.js",
        "/build/chunks/get-sharing-bucket-expiration-label-CzomMGXb.js",
        "/build/chunks/format-4Kq6c7g1.js",
        "/build/chunks/textarea-keydown-enter-submit-CipxD2L_.js",
        "/build/chunks/auth-form-PuyrRK6N.js",
        "/build/chunks/result-CAafE33N.js",
        "/build/chunks/date-time-ls5LZsUX.js",
        "/build/chunks/client-only-BczqNwUQ.js",
        "/build/chunks/script-AKGWJTdR.js",
        "/build/chunks/create-lazy-singleton-nczC2Aqe.js",
        "/build/chunks/startWith-D6GmgBIa.js",
        "/build/chunks/firstValueFrom-A2B9aB4_.js",
        "/build/chunks/mergeWith-CW1bjSkm.js",
        "/build/chunks/merge-sFKZucBs.js",
        "/build/chunks/BehaviorSubject-DXmu5-9D.js",
        "/build/chunks/VerificationStatusEnum-BMWjV5ER.js",
        "/build/chunks/AccountSubscriptionTier-Cz37hh3K.js",
        "/build/chunks/UsStateCodeAlpha2-JNjTMX_I.js",
        "/build/chunks/combineLatest-B-eaUnSB.js",
        "/build/chunks/link-button-0u0k6ShQ.js",
        "/build/chunks/root-data-from-meta-D6MxA-wH.js",
        "/build/chunks/format-crypto-currency-ywX7BMAm.js",
        "/build/chunks/CryptoCurrency-H89N9OUl.js",
        "/build/chunks/lmwr-context-gGILrNJS.js",
        "/build/chunks/tab-button-B9masPp5.js",
        "/build/chunks/error-CMZhxXBr.js",
        "/build/chunks/preload-helper-ckwbz45p.js",
        "/build/chunks/limewire-logo-Dqzw9EF0.js",
        "/build/chunks/CompositeItem-CDHQO3Bq.js",
        "/build/chunks/arrow-right-icon-MKNL3ZLR.js",
        "/build/chunks/use-logout-2r9-Iv6K.js",
        "/build/chunks/use-typed-explicit-fetcher-8EVVP3LO.js",
        "/build/chunks/creator-DZkRxswE.js",
        "/build/chunks/use-copyright-DfriYUUN.js",
        "/build/chunks/app-integration-provider-eroOOUkO.js",
        "/build/chunks/app-integration-loading-Stpofhhd.js",
        "/build/chunks/use-self-cancel-interval-Dvxku-cX.js",
        "/build/chunks/actionable-elements-BiUyVnPQ.js",
        "/build/chunks/createFormData-DNO6HZGs.js",
        "/build/chunks/asset-aspect-ratio-BohSO0Ps.js",
        "/build/chunks/auth-context-C4B4EndV.js",
        "/build/chunks/index-C_cZ4Myj.js",
        "/build/chunks/use-issue-two-factor-code-C-lTNfXJ.js",
        "/build/chunks/authenticity-token-jepGkwPV.js",
        "/build/chunks/auth-form-validation-BU6Liuu6.js",
        "/build/chunks/auth-window-messenger-BT_sk8fK.js",
        "/build/chunks/use-external-wallet-d47QtwzM.js",
        "/build/chunks/divider-Rf5dTIjq.js"
      ],
      "css": []
    },
    "routes/__root/__landing": {
      "id": "routes/__root/__landing",
      "parentId": "routes/__root",
      "hasAction": false,
      "hasLoader": false,
      "hasClientAction": false,
      "hasClientLoader": false,
      "hasClientMiddleware": false,
      "hasDefaultExport": true,
      "hasErrorBoundary": false,
      "module": "/build/chunks/entry/__landing-Blx8tv7_.js",
      "imports": [
        "/build/chunks/chunk-EVOBXE3Y-9W61Xgs7.js"
      ],
      "css": []
    },
    "routes/__root/__landing/index": {
      "id": "routes/__root/__landing/index",
      "parentId": "routes/__root/__landing",
      "index": true,
      "hasAction": false,
      "hasLoader": true,
      "hasClientAction": false,
      "hasClientLoader": false,
      "hasClientMiddleware": false,
      "hasDefaultExport": true,
      "hasErrorBoundary": false,
      "module": "/build/chunks/entry/index-DRPttMQE.js",
      "imports": [
        "/build/chunks/index-BZfNFPH3.js",
        "/build/chunks/chunk-EVOBXE3Y-9W61Xgs7.js",
        "/build/chunks/StripeModal-CVKIXlVh.js",
        "/build/chunks/runtime-2_b2CLRu.js",
        "/build/chunks/AccountSubscriptionTier-Cz37hh3K.js",
        "/build/chunks/file-sharing-provider-rzg-sq63.js",
        "/build/chunks/startWith-D6GmgBIa.js",
        "/build/chunks/firstValueFrom-A2B9aB4_.js",
        "/build/chunks/mergeWith-CW1bjSkm.js",
        "/build/chunks/merge-sFKZucBs.js",
        "/build/chunks/BehaviorSubject-DXmu5-9D.js",
        "/build/chunks/get-api-GQqJvRNy.js",
        "/build/chunks/result-CAafE33N.js",
        "/build/chunks/runtime-a9fv597q.js",
        "/build/chunks/VerificationStatusEnum-BMWjV5ER.js",
        "/build/chunks/UsStateCodeAlpha2-JNjTMX_I.js",
        "/build/chunks/combineLatest-B-eaUnSB.js",
        "/build/chunks/form-schema-utils-BpIBEm7l.js",
        "/build/chunks/types-DL0SRdtb.js",
        "/build/chunks/use-state-ref-2F-FBlDX.js",
        "/build/chunks/use-callback-ref-FXC1dIJW.js",
        "/build/chunks/use-const-Ctj4Pbrd.js",
        "/build/chunks/modal-content-window-title-header-B4KyUpSA.js",
        "/build/chunks/index-kJLDGboo.js",
        "/build/chunks/toggle-group-kkI2GucT.js",
        "/build/chunks/focus-visible-outline-D4EmqDoY.js",
        "/build/chunks/resolve-to-node-Bl44lgnH.js",
        "/build/chunks/noop-BjFrJKj1.js",
        "/build/chunks/textarea-CedQn1pA.js",
        "/build/chunks/base-button-Dn-aSjlR.js",
        "/build/chunks/form-validation-BVQTbEu8.js",
        "/build/chunks/alert-BuFjbp8h.js",
        "/build/chunks/use-self-cancel-timeout-CylTudUM.js",
        "/build/chunks/use-self-cancel-interval-Dvxku-cX.js",
        "/build/chunks/createFormData-DNO6HZGs.js",
        "/build/chunks/button-WTfLYYUY.js",
        "/build/chunks/link-button-0u0k6ShQ.js",
        "/build/chunks/get-sharing-bucket-expiration-label-CzomMGXb.js",
        "/build/chunks/auth-form-PuyrRK6N.js",
        "/build/chunks/env-context-Crfubjd7.js",
        "/build/chunks/use-typed-explicit-fetcher-8EVVP3LO.js",
        "/build/chunks/use-issue-two-factor-code-C-lTNfXJ.js",
        "/build/chunks/authenticity-token-jepGkwPV.js",
        "/build/chunks/auth-form-validation-BU6Liuu6.js",
        "/build/chunks/auth-context-C4B4EndV.js",
        "/build/chunks/navigation-link-Dew0cAKK.js",
        "/build/chunks/app-integration-provider-eroOOUkO.js",
        "/build/chunks/app-integration-loading-Stpofhhd.js",
        "/build/chunks/client-only-BczqNwUQ.js",
        "/build/chunks/auth-window-messenger-BT_sk8fK.js",
        "/build/chunks/use-external-wallet-d47QtwzM.js",
        "/build/chunks/preload-helper-ckwbz45p.js",
        "/build/chunks/create-lazy-singleton-nczC2Aqe.js",
        "/build/chunks/divider-Rf5dTIjq.js",
        "/build/chunks/user-context-DcxnCGfr.js",
        "/build/chunks/format-crypto-currency-ywX7BMAm.js",
        "/build/chunks/CryptoCurrency-H89N9OUl.js",
        "/build/chunks/error-CMZhxXBr.js",
        "/build/chunks/index-C_cZ4Myj.js",
        "/build/chunks/lmwr-context-gGILrNJS.js",
        "/build/chunks/PaymentTypeEnum-BIW0bXfI.js",
        "/build/chunks/actionable-elements-BiUyVnPQ.js",
        "/build/chunks/api-context-CI3M1bMX.js",
        "/build/chunks/contract-DCyJtHIA.js",
        "/build/chunks/forward-platform-action-B7m92-wH.js",
        "/build/chunks/content-item-icon-CWSsBIAk.js",
        "/build/chunks/content-item-name-DlF1OtJB.js",
        "/build/chunks/arrow-right-icon-MKNL3ZLR.js",
        "/build/chunks/feedback-tooltip-DzcbJ7Uo.js",
        "/build/chunks/file-name-wPVW7C-B.js",
        "/build/chunks/dropdown-menu-item-DBh_jOFm.js",
        "/build/chunks/CompositeItem-CDHQO3Bq.js",
        "/build/chunks/file-descriptor-6NH0AYhf.js",
        "/build/chunks/format-4Kq6c7g1.js",
        "/build/chunks/textarea-prepare-enter-submit-DoydCyck.js",
        "/build/chunks/textarea-keydown-enter-submit-CipxD2L_.js",
        "/build/chunks/default-shell-layout-Cm20i_GI.js",
        "/build/chunks/tab-button-B9masPp5.js",
        "/build/chunks/creator-name-CljkNgas.js",
        "/build/chunks/asset-aspect-ratio-BohSO0Ps.js",
        "/build/chunks/shared-DwIwScEe.js",
        "/build/chunks/limewire-logo-Dqzw9EF0.js",
        "/build/chunks/use-logout-2r9-Iv6K.js",
        "/build/chunks/creator-DZkRxswE.js",
        "/build/chunks/use-copyright-DfriYUUN.js",
        "/build/chunks/navigation-tabs-2caq_oyG.js",
        "/build/chunks/google-adsense-ad-aPLRVnSn.js",
        "/build/chunks/QueryClientProvider-eTMApExI.js",
        "/build/chunks/date-time-ls5LZsUX.js",
        "/build/chunks/script-AKGWJTdR.js",
        "/build/chunks/use-endless-scroll-BXQnXQea.js",
        "/build/chunks/copy-input-CuB6aqkr.js",
        "/build/chunks/scroll-into-view-DgeChBha.js",
        "/build/chunks/page-column-layout-7pRCrlts.js",
        "/build/chunks/get-default-seo-preview-image-CuRl7GKl.js",
        "/build/chunks/root-data-from-meta-D6MxA-wH.js",
        "/build/chunks/share-nearby-provider-z51Inzez.js",
        "/build/chunks/use-sse-CIElAM2L.js",
        "/build/chunks/payment-credits-icon-COHsVKfR.js"
      ],
      "css": []
    },
    "routes/__root/$": {
      "id": "routes/__root/$",
      "parentId": "routes/__root",
      "path": "*",
      "hasAction": false,
      "hasLoader": true,
      "hasClientAction": false,
      "hasClientLoader": false,
      "hasClientMiddleware": false,
      "hasDefaultExport": true,
      "hasErrorBoundary": false,
      "module": "/build/chunks/entry/_-D3rIHRsP.js",
      "imports": [
        "/build/chunks/chunk-EVOBXE3Y-9W61Xgs7.js",
        "/build/chunks/page-error-404-DzJrfiEl.js",
        "/build/chunks/page-error-404-Ba3LfCNG.js",
        "/build/chunks/page-error-BJg5EwrZ.js",
        "/build/chunks/page-error-content-C6qE9j0k.js",
        "/build/chunks/index-kJLDGboo.js",
        "/build/chunks/shared-DwIwScEe.js",
        "/build/chunks/button-WTfLYYUY.js",
        "/build/chunks/base-button-Dn-aSjlR.js",
        "/build/chunks/focus-visible-outline-D4EmqDoY.js",
        "/build/chunks/default-shell-layout-Cm20i_GI.js",
        "/build/chunks/format-crypto-currency-ywX7BMAm.js",
        "/build/chunks/CryptoCurrency-H89N9OUl.js",
        "/build/chunks/lmwr-context-gGILrNJS.js",
        "/build/chunks/user-context-DcxnCGfr.js",
        "/build/chunks/runtime-2_b2CLRu.js",
        "/build/chunks/AccountSubscriptionTier-Cz37hh3K.js",
        "/build/chunks/navigation-link-Dew0cAKK.js",
        "/build/chunks/tab-button-B9masPp5.js",
        "/build/chunks/toggle-group-kkI2GucT.js",
        "/build/chunks/use-state-ref-2F-FBlDX.js",
        "/build/chunks/use-callback-ref-FXC1dIJW.js",
        "/build/chunks/use-const-Ctj4Pbrd.js",
        "/build/chunks/resolve-to-node-Bl44lgnH.js",
        "/build/chunks/noop-BjFrJKj1.js",
        "/build/chunks/form-validation-BVQTbEu8.js",
        "/build/chunks/form-schema-utils-BpIBEm7l.js",
        "/build/chunks/types-DL0SRdtb.js",
        "/build/chunks/alert-BuFjbp8h.js",
        "/build/chunks/textarea-CedQn1pA.js",
        "/build/chunks/use-self-cancel-timeout-CylTudUM.js",
        "/build/chunks/use-self-cancel-interval-Dvxku-cX.js",
        "/build/chunks/createFormData-DNO6HZGs.js",
        "/build/chunks/env-context-Crfubjd7.js",
        "/build/chunks/error-CMZhxXBr.js",
        "/build/chunks/get-api-GQqJvRNy.js",
        "/build/chunks/result-CAafE33N.js",
        "/build/chunks/api-context-CI3M1bMX.js",
        "/build/chunks/preload-helper-ckwbz45p.js",
        "/build/chunks/client-only-BczqNwUQ.js",
        "/build/chunks/create-lazy-singleton-nczC2Aqe.js",
        "/build/chunks/modal-content-window-title-header-B4KyUpSA.js",
        "/build/chunks/creator-name-CljkNgas.js",
        "/build/chunks/asset-aspect-ratio-BohSO0Ps.js",
        "/build/chunks/VerificationStatusEnum-BMWjV5ER.js",
        "/build/chunks/limewire-logo-Dqzw9EF0.js",
        "/build/chunks/CompositeItem-CDHQO3Bq.js",
        "/build/chunks/arrow-right-icon-MKNL3ZLR.js",
        "/build/chunks/use-logout-2r9-Iv6K.js",
        "/build/chunks/file-sharing-provider-rzg-sq63.js",
        "/build/chunks/startWith-D6GmgBIa.js",
        "/build/chunks/firstValueFrom-A2B9aB4_.js",
        "/build/chunks/mergeWith-CW1bjSkm.js",
        "/build/chunks/merge-sFKZucBs.js",
        "/build/chunks/BehaviorSubject-DXmu5-9D.js",
        "/build/chunks/runtime-a9fv597q.js",
        "/build/chunks/UsStateCodeAlpha2-JNjTMX_I.js",
        "/build/chunks/combineLatest-B-eaUnSB.js",
        "/build/chunks/link-button-0u0k6ShQ.js",
        "/build/chunks/use-typed-explicit-fetcher-8EVVP3LO.js",
        "/build/chunks/creator-DZkRxswE.js",
        "/build/chunks/use-copyright-DfriYUUN.js",
        "/build/chunks/app-integration-provider-eroOOUkO.js",
        "/build/chunks/app-integration-loading-Stpofhhd.js"
      ],
      "css": []
    }
  },
  "url": "/build/assets/manifest-72109a0f.js",
  "version": "72109a0f"
};
  window.__reactRouterRouteModules = {"root":route0,"routes/__root":route1,"routes/__root/d/$id":route2};

import("/build/chunks/entry/entry.client-DazuTZIh.js");</script><script>((storageKey2, restoreKey) => {
    if (!window.history.state || !window.history.state.key) {
      let key = Math.random().toString(32).slice(2);
      window.history.replaceState({ key }, "");
    }
    try {
      let positions = JSON.parse(sessionStorage.getItem(storageKey2) || "{}");
      let storedY = positions[restoreKey || window.history.state.key];
      if (typeof storedY === "number") {
        window.scrollTo(0, storedY);
      }
    } catch (error) {
      console.error(error);
      sessionStorage.removeItem(storageKey2);
    }
  })("react-router-scroll-positions", null)</script><!--$--><script>window.__reactRouterContext.streamController.enqueue("[{\"_1\":2,\"_3\":-5,\"_4\":-5},\"loaderData\",{\"_5\":6,\"_7\":8},\"actionData\",\"errors\",\"routes/__root\",{\"_106\":-7,\"_107\":-5,\"_108\":-7,\"_109\":110,\"_111\":112,\"_113\":-7,\"_114\":-7,\"_115\":-5,\"_116\":36,\"_117\":-7,\"_118\":-7,\"_119\":120,\"_121\":-7,\"_122\":-5},\"routes/__root/d/$id\",{\"_9\":10,\"_11\":12},\"sharingId\",\"4TvIn\",\"sharingBucketContentData\",{\"_13\":14,\"_15\":16},\"ok\",true,\"value\",{\"_17\":18,\"_19\":20,\"_21\":22,\"_23\":14},\"sharingBucket\",{\"_25\":55,\"_82\":-7,\"_83\":84,\"_85\":86,\"_87\":88,\"_89\":90,\"_9\":10,\"_91\":26,\"_92\":93,\"_94\":63,\"_95\":96,\"_37\":97,\"_39\":98,\"_35\":36,\"_99\":100,\"_101\":102,\"_103\":102,\"_104\":36},\"contentItemList\",[52],\"fileEncryptionKeys\",[24],\"displayAds\",{\"_25\":26,\"_27\":28,\"_29\":30,\"_31\":32,\"_33\":34,\"_35\":36,\"_37\":38,\"_39\":40},\"id\",\"56e412f7-9fcf-49b0-8485-e8488102b640\",\"publicKey\",\"BP/oVtj6TW5nHQtZ9rwzVxjbbA1gV9sg/VOQaXSwl1AenYS7RT6IJqN22hioliQL3T8Fr7aMhpyrFVaOAH6ObZw=\",\"privateKeys\",[45],\"encryptedPassphrase\",\"upKIpnSZfTcnRxF2e7BhdANg0FtAiQJXOYc=\",\"passphraseWrappedPrivateKey\",\"dSXaBGuC+GIsC3JT9D8S7ptINqDOgXjzHM57Gq74g0QBVqn9jTLEnA==\",\"deleted\",false,\"createdDate\",[\"D\",1778000409346],\"lastModifiedTimestamp\",{\"_41\":42,\"_43\":44},\"time\",1778000450,\"increment\",10,{\"_46\":47,\"_48\":49,\"_50\":51},\"encryptedPrivateKey\",\"1BRagsOCloQkie9jg+H90vv36/L6DHWdzR3gzoGnc7VDJwBLIl+vgw==\",\"encryptedByKeyType\",\"USER_ENCRYPTION_KEY\",\"encryptedByKeyId\",\"001d3956-52e1-4490-af62-1db1a02efd5b\",{\"_25\":53,\"_54\":55,\"_56\":57,\"_58\":59,\"_60\":61,\"_62\":63,\"_64\":65,\"_66\":67,\"_68\":26,\"_69\":70,\"_71\":72,\"_73\":74,\"_75\":-7,\"_37\":76,\"_39\":77,\"_35\":36},\"bf677829-dae6-4d03-bcc3-9aeaca7b81aa\",\"originalSharingBucketId\",\"71b80f17-e587-49e9-815d-7760bdb34206\",\"s3Status\",\"UPLOADED\",\"itemType\",\"OTHER\",\"mediaType\",\"text/x-sh\",\"size\",13370,\"nameEncrypted\",\"TfPRb0MSIYDhn34C4cD6I14jldmoXhvPlGCDZg==\",\"sha1Encrypted\",\"Yl+V6NLbfG3gENaftzu2orG1mDw5j0av4XxyEE8kUT6RqjTk\",\"baseFileEncryptionKeyId\",\"ephemeralPublicKey\",\"BKgUnpRKcXFat7bP3MhQi4FNPDrL7B64DqrSCanNVdyGVCOutY2nMVNqHfuPs2tOYiackpOMfdViSrKFQSQQu/c=\",\"metadata\",{\"_80\":81},\"previews\",[],\"nsfw\",[\"D\",1778000409999],{\"_41\":78,\"_43\":79},1778000420,70,\"metadataType\",\"unknown\",\"ownerId\",\"clientDeviceId\",\"79899a6b-8061-413f-9ec9-b21ff6f54a72\",\"ownerNick\",\"anonymous\",\"sharingStatus\",\"SHARED\",\"sharingPermission\",\"VIEWER\",\"primaryEncryptionKeyId\",\"contentItemIds\",[53],\"totalFileSize\",\"name\",\"V84_PATCH.sh\",[\"D\",1778000409998],{\"_41\":42,\"_43\":105},\"expiresAt\",[\"D\",1778605210501],\"downloadCounter\",0,\"publicDownloadCounter\",\"pinned\",8,\"promotionBanner\",\"platformBanner\",\"cacheId\",\"env\",{\"_129\":130,\"_131\":132,\"_133\":36,\"_134\":36,\"_135\":136,\"_137\":138,\"_139\":140,\"_141\":142,\"_143\":144,\"_145\":146,\"_147\":148,\"_149\":150,\"_151\":152},\"csrfToken\",\"UWK51U7nEwV3TthEf8DdTollfYY-SkLUcI9oL1RntqEhT7xJVVEoj_QZX46hzJP6mcVDLt9eTM0qALtNDZo1gQ\",\"selfClientId\",\"selfCsrf\",\"referrer\",\"isAuthenticated\",\"self\",\"lmwrBalance\",\"lmwrExchangeRates\",{\"_123\":124,\"_125\":126,\"_127\":128},\"aiCredits\",\"appIntegration\",\"currency\",\"LMWR\",\"exchangeRate\",0.02001244165098989,\"percentageChange24h\",-3.73897454,\"NOW\",[\"D\",1778000498958],\"CLIENT_BASE_URL\",\"https://limewire.com\",\"IS_DEV\",\"IS_STAGING\",\"API_BASE_URL\",\"https://api.limewire.com\",\"GA_TRACKING_ID\",\"GTM-NNHHMZ9\",\"LIMEWIRE_FREE_USER_ID\",\"7f219511-0a09-403c-a94b-caa56419b5f8\",\"LIMEWIRE_PRO_USER_ID\",\"1e2c66a9-7073-499b-86fb-b134a088ce44\",\"SENTRY_DSN\",\"https://3914d239cc544007a8bc3b33c2e276e7:375389f9b8fc4a58aac7ddf053335cd6@o4505008135340032.ingest.sentry.io/4505114707099648\",\"SENTRY_ENVIRONMENT\",\"production\",\"SENTRY_PROJECT\",\"limewire-js-remix\",\"GIT_RELEASE\",\"e0f62ac00c91b4e3883a5c03915e94bfbcb608c0\",\"STORYBLOCK_SPACE_ACCESS_TOKEN\",\"jmGRmWycHD5MvliLQXFkXAtt\"]\n");</script><!--$--><script>window.__reactRouterContext.streamController.close();</script><!--/$--><!--/$--></body></html>