#!/usr/bin/env python3
"""Write cas_stocks.txt — the stocks that close by auction — from Kite.

CAS Phase 1 covers "Category I" securities, which SEBI defines as the stocks
carrying F&O contracts. That set is exactly the F&O underlying list, and it
changes at every exchange review, so derive it from the live instrument dump
rather than maintaining a list by hand.

Run on the droplet, where the Kite keys live:

    python3 scripts/refresh_cas_stocks.py                 # writes ./cas_stocks.txt
    python3 scripts/refresh_cas_stocks.py --out /path/cas_stocks.txt
    python3 scripts/refresh_cas_stocks.py --dry-run       # print, write nothing

garuda/market.py reads the file at import, falling back to fno_stocks.txt when
it is absent, so nothing breaks if this has never been run.
"""

import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from garuda.feed import KiteFeed                       # noqa: E402
from garuda.market import cas_universe_from_instruments  # noqa: E402

HEADER = """\
# CATEGORY I — the NSE stocks whose closing price comes from the Closing
# Auction Session (15:15-15:35) instead of the old last-30-minute VWAP.
# One symbol per line, '#' = comment.
#
# Generated by scripts/refresh_cas_stocks.py from the live Kite F&O instrument
# dump on {stamp}. The exchange revises the F&O universe periodically —
# re-run this after each review. Delete the file to fall back to fno_stocks.txt.
"""


def main() -> int:
    args = sys.argv[1:]
    dry = "--dry-run" in args
    out = Path("cas_stocks.txt")
    if "--out" in args:
        out = Path(args[args.index("--out") + 1])

    feed = KiteFeed()
    if not feed.live():
        print("no Kite session — set KITE_API_KEY and KITE_TOKEN_FILE, "
              "then run this on the droplet", file=sys.stderr)
        return 2

    nfo = feed.kite.instruments("NFO")
    nse = feed.kite.instruments("NSE")
    symbols = cas_universe_from_instruments(nfo, nse)
    if not symbols:
        print("instrument dump produced no F&O underlyings — refusing to write "
              "an empty list", file=sys.stderr)
        return 1

    body = HEADER.format(stamp=date.today().isoformat()) + "\n".join(symbols) + "\n"
    if dry:
        print(body, end="")
        print(f"\n({len(symbols)} symbols, nothing written)", file=sys.stderr)
        return 0

    out.write_text(body)
    print(f"wrote {out} — {len(symbols)} Category I symbols")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
